### ISSUE TITLE
Irresponsive image

### ISSUE THREAD

**Issue by foxy4096** [nmasi322/glavid_space#2]
You should see this
![image](https://user-images.githubusercontent.com/54215788/143742528-cc96a7a6-3fd8-4339-a852-5e5e5f08283c.png)

Screen Resolution: 1600X900

**Comment by nmasi322** [comment]
![IMG_20211128_104326_282](https://user-images.githubusercontent.com/74861009/143763032-82ad892a-0e96-46fd-8328-bd76c1cc1671.jpg)
Thanks for the correction 😸, try to refresh your page now.

**Comment by foxy4096** [comment]
Yup its good now!

**Comment by foxy4096** [comment]
Oh yes, I remember my display zoom was like 125%
![image](https://user-images.githubusercontent.com/54215788/143763845-3e81b9ea-6e54-4b5a-9921-a51b1cac0017.png)

If I turn it to 100% it would look normal.

**Comment by nmasi322** [comment]
Glad it's all good now.
